/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "var(--surface-container-highest)",
        "outline-variant": "var(--outline-variant)",
        "tertiary": "var(--tertiary)",
        "tertiary-dim": "var(--tertiary-dim)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "error-dim": "var(--error-dim)",
        "on-background": "var(--on-background)",
        "tertiary-container": "var(--tertiary-container)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary": "var(--on-secondary)",
        "on-primary": "var(--on-primary)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-surface-variant": "var(--on-surface-variant)",
        "secondary-dim": "var(--secondary-dim)",
        "primary-fixed": "var(--primary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "primary-container": "var(--primary-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-container": "var(--surface-container)",
        "outline": "var(--outline)",
        "surface-dim": "var(--surface-dim)",
        "error-container": "var(--error-container)",
        "surface-variant": "var(--surface-variant)",
        "on-surface": "var(--on-surface)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-tint": "var(--surface-tint)",
        "on-error": "var(--on-error)",
        "secondary": "var(--secondary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "background": "var(--background)",
        "primary-dim": "var(--primary-dim)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface": "var(--surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-error-container": "var(--on-error-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "primary": "var(--primary)",
        "error": "var(--error)",
        "on-primary-container": "var(--on-primary-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
